src/Entity/Vegetable.php
<?php

namespace App\Entity;

use App\Repository\VegetableRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VegetableRepository::class)]
class Vegetable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Family = null;

    #[ORM\Column(length:255)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getFamily(): ?string
    {
        return $this->Family;
    }

    public function setFamily(string $Family): self
    {
        $this->Family = $Family;

        return $this;
    }

    public function getImage() : ?string 
    {
        return $this->image;
    }

    public function setImage(string $image) : self 
    {
        $this->image = $image;
        
        return $this;
    }
}

src/Form/VegetableType.php
<?php

namespace App\Form;

use App\Entity\Vegetable;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VegetableType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('Description')
            ->add('Family')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Vegetable::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home_index')]
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }
}

src/Controller/VegetableController.php
<?php

namespace App\Controller;

use App\Entity\Vegetable;
use App\Form\VegetableType;
use App\Repository\VegetableRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class VegetableController extends AbstractController
{

    #[Route('/vegetable', name: 'vegetable_index')]
    public function index(VegetableRepository $vegetableRepository): Response
    {
        return $this->render('vegetable/index.html.twig', [
            'vegetables' => $vegetableRepository->findAll()
        ]);
    }

    #[Route('vegetable/add',name:'vegetable_add')]
    public function add(Request $request, VegetableRepository $vegetableRepository) : Response
    {
        $vegatable = new Vegetable();

        $form = $this->createForm(VegetableType::class,$vegatable);

        $form->handleRequest($request);

        if($form->isValid() && $form->isSubmitted())
        {
            $vegetableRepository->save($vegatable,true);

            return $this->redirectToRoute('vegetable_index');
        }

        return $this->render('vegetable/add.html.twig',[
            'form' => $form
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Le potager!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/becode/Bureau/symfony/Garden/src/Controller/HomeController.php'|file_link(0) }}">src/Controller/HomeController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/becode/Bureau/symfony/Garden/templates/home/index.html.twig'|file_link(0) }}">templates/home/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/vegetable/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un légume | {{ parent() }}{% endblock %}

{% block body %}


<div class="container mx-auto my-5">
   {{form_start(form,{
    'action': path('vegetable_add'),
    'method': 'POST',
   })}}

    <div class="w-full">
        <input 
            type="text"
            name="{{ field_name(form.name)}}" 
            placeholder="Nom du légume"
            value="{{field_value(form.name)}}"
            class="bg-gray-50 p-4 outline-none border w-full">
    </div>

   <div class="my-5 w-full">
        <textarea
            name="{{field_name(form.Description)}}"
            placeholder="Description du légume"
            class="bg-gray-50 p-4 outline-none border w-full"></textarea>
   </div>

   <div class="w-full">
          <input 
            type="text"
            name="{{ field_name(form.Family)}}" 
            placeholder="Famille du légume"
            value="{{field_value(form.Family)}}"
            class="bg-gray-50 p-4 outline-none border w-full">
   </div>

     <div class="w-full my-5">
          <input 
            type="text"
            name="{{ field_name(form.image)}}" 
            placeholder="Url image du légume"
            value="{{field_value(form.image)}}"
            class="bg-gray-50 p-4 outline-none border w-full">
   </div>

   <div>
        <input type="submit" class="p-4 bg-violet-500 text-white rounded">
   </div>


   {{form_end(form)}}
</div>

{% endblock %}

templates/vegetable/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Légumes | {{ parent() }}{% endblock %}

{% block body %}


<div class="container mx-auto">
    <div class="grid grid-cols-4 gap-10 my-5">
        {% for vegetable in vegetables %}
            <div class="bg-gray-50 shadow-lg rounded border">
                <img src="{{vegetable.image}}" alt="{{vegetable.name}}" class="w-full h-48 object-cover rounded-t">
                <div class="p-4">
                    <h2 class="text-3xl font-black">{{vegetable.name}}</h2>
                    <p class="font-light my-4">{{vegetable.description}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}